// app/src/components/SettingsPanel.svelte
<script lang="ts">
  import { Cpu, Palette } from "@lucide/svelte";

  import AppearancePage from "@/components/settings/AppearancePage.svelte";
  import ModelsPage from "@/components/settings/ModelsPage.svelte";
  import { S } from "@/strings";

  const PAGES = [
    { id: "models", label: S.modelsPage, Icon: Cpu, Page: ModelsPage },
    { id: "appearance", label: S.appearancePage, Icon: Palette, Page: AppearancePage },
  ];

  // Lands on the models page each time: it is the one a new install has to visit.
  let active = $state(PAGES[0].id);
  const Page = $derived(PAGES.find((p) => p.id === active)!.Page);
</script>

<section class="flex min-h-0 min-w-0 flex-1 flex-col">
  <div class="border-b px-6 pb-2">
    <div role="tablist" aria-label={S.settings} class="flex gap-1">
      {#each PAGES as { id, label, Icon } (id)}
        <button
          role="tab"
          aria-selected={active === id}
          class={[
            "flex items-center gap-1.5 rounded-md px-2.5 py-1 text-sm transition-colors hover:bg-accent hover:text-foreground",
            active === id ? "bg-accent font-medium text-foreground" : "text-muted-foreground",
          ]}
          onclick={() => (active = id)}
        >
          <Icon class="size-4 shrink-0" />
          {label}
        </button>
      {/each}
    </div>
  </div>
  <div class="min-h-0 flex-1 overflow-y-auto px-6 pt-5 pb-10">
    <div class="mx-auto max-w-3xl" role="tabpanel">
      <Page />
    </div>
  </div>
</section>

// apps/desktop/src/components/SettingsPanel.tsx
// Settings, in the main panel, as pages.
//
// A panel and not a dialog. Keys are the one thing a new install cannot start without, and
// a provider's pane is where the user finds out whether the key they pasted took — which is
// reading, comparing and coming back, not the one decision a modal is for. A modal also
// takes the window hostage: the no-key banner that sent the user here is behind it, and so
// is the model picker the key is about to fill.
//
// Pages, because settings only grow. A strip across the top and one component per page: a
// page is a row in `PAGES` and a file in `components/settings`, and it brings its own
// queries with it — nothing here is shared state to thread through, and a page the user has
// not opened has not mounted, so it costs nothing to add one.

import { Cpu, Palette } from "lucide-react";

import { AppearancePage } from "@/components/settings/AppearancePage";
import { ModelsPage } from "@/components/settings/ModelsPage";
import { Tabs, TabsList, TabsPanel, TabsTab } from "@/components/ui/tabs";
import { S } from "@/strings";

const PAGES = [
  { id: "models", label: S.modelsPage, Icon: Cpu, Page: ModelsPage },
  { id: "appearance", label: S.appearancePage, Icon: Palette, Page: AppearancePage },
];

export function SettingsPanel() {
  return (
    <section className="flex min-h-0 min-w-0 flex-1 flex-col">
      {/* Uncontrolled: which page the user was last on is not worth remembering across a
          relaunch, and the panel is rebuilt each time it opens — which lands on the models
          page, the one a new install has to visit. */}
      <Tabs defaultValue={PAGES[0].id} className="flex min-h-0 flex-1 flex-col">
        <div className="border-b px-6 pt-3">
          <h1 className="text-xl font-semibold">{S.settings}</h1>
          <TabsList aria-label={S.settings} className="mt-3 gap-1">
            {PAGES.map(({ id, label, Icon }) => (
              <TabsTab key={id} value={id}>
                <Icon className="size-4 shrink-0" />
                {label}
              </TabsTab>
            ))}
          </TabsList>
        </div>
        <div className="min-h-0 flex-1 overflow-y-auto px-6 pt-5 pb-10">
          <div className="mx-auto max-w-3xl">
            {PAGES.map(({ id, Page }) => (
              <TabsPanel key={id} value={id}>
                <Page />
              </TabsPanel>
            ))}
          </div>
        </div>
      </Tabs>
    </section>
  );
}
