// apps/desktop/src/components/viewers/PdfViewer.tsx
// A PDF, drawn by the app rather than by the platform.
//
// The built-in viewer was the obvious choice and it is the one this replaces. It renders
// well, but it paints an opaque backdrop of its own over the whole element, so the band
// around a page is grey in a window that is not — and no CSS reaches it. Measured, not
// assumed: a red background behind a narrow page in an `<iframe>` never appears. Owning the
// rendering is the only way to own what surrounds it.
//
// What that costs is the platform's selection, search and printing, and ~350 KB of
// renderer. The renderer is imported lazily, so only a PDF pays for it.
//
// Pages are drawn as they come into view. A report is a hundred pages and a canvas each is
// a hundred bitmaps at device resolution; the placeholders carry each page's real size, so
// the scrollbar is right from the first frame and nothing jumps as pages fill in.

import { useEffect, useRef, useState } from "react";

import { useBytes } from "@/lib/useBytes";
import { S } from "@/strings";

/** Page geometry, known before anything is rasterised. */
interface Page {
  index: number;
  width: number;
  height: number;
}

type Task = Awaited<ReturnType<typeof openDocument>>;
type Doc = Awaited<Task["promise"]>;

/**
 * The loading task, not the document: releasing a PDF means destroying the task, which is
 * what tears down the worker with it. The document is on its `promise`.
 */
async function openDocument(bytes: ArrayBuffer) {
  const pdfjs = await import("pdfjs-dist");
  // The worker is bundled from our own origin, which is what `script-src 'self'` allows.
  pdfjs.GlobalWorkerOptions.workerSrc = new URL(
    "pdfjs-dist/build/pdf.worker.min.mjs",
    import.meta.url,
  ).toString();
  // The buffer is transferred to the worker, so it must not be the one `useBytes` holds —
  // a re-render would hand over an already-detached buffer.
  return pdfjs.getDocument({ data: bytes.slice(0) });
}

/** One page: its own size until it is on screen, a canvas once it has been. */
function PageView({ doc, page, width }: { doc: Doc; page: Page; width: number }) {
  const host = useRef<HTMLDivElement>(null);
  const [visible, setVisible] = useState(false);
  const scale = width > 0 ? width / page.width : 1;

  useEffect(() => {
    const el = host.current;
    if (!el || visible) return;
    // A margin, so a page is drawn just before it is scrolled to rather than as it lands.
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) setVisible(true);
      },
      { rootMargin: "400px" },
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, [visible]);

  useEffect(() => {
    if (!visible || !host.current || scale <= 0) return;
    const into = host.current;
    let live = true;
    let task: { cancel: () => void } | null = null;
    void doc.getPage(page.index).then((p) => {
      if (!live) return;
      // Drawn at device resolution and laid out at CSS size, or the text is soft on a
      // retina display.
      const dpr = window.devicePixelRatio || 1;
      const viewport = p.getViewport({ scale: scale * dpr });
      const canvas = document.createElement("canvas");
      canvas.width = Math.floor(viewport.width);
      canvas.height = Math.floor(viewport.height);
      canvas.style.width = "100%";
      canvas.style.display = "block";
      const ctx = canvas.getContext("2d");
      if (!ctx) return;
      const render = p.render({ canvas, canvasContext: ctx, viewport });
      task = render;
      void render.promise.then(
        () => {
          if (live) into.replaceChildren(canvas);
        },
        () => {},
      );
    });
    return () => {
      live = false;
      task?.cancel();
    };
  }, [visible, doc, page.index, scale]);

  return (
    <div
      ref={host}
      className="bg-card shadow-sm"
      // The page's own aspect, so the column is the right height before it is drawn.
      style={{ aspectRatio: `${page.width} / ${page.height}` }}
    />
  );
}

export function PdfViewer({ path }: { path: string }) {
  const bytes = useBytes(path);
  const column = useRef<HTMLDivElement>(null);
  const [doc, setDoc] = useState<Doc | null>(null);
  const [pages, setPages] = useState<Page[]>([]);
  const [failed, setFailed] = useState(false);
  const [width, setWidth] = useState(0);

  // The column's width decides the render scale, and it changes with the window and with
  // the sidebar being collapsed.
  useEffect(() => {
    const el = column.current;
    if (!el) return;
    const observer = new ResizeObserver(([entry]) => setWidth(entry.contentRect.width));
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    if (bytes.state !== "ready") return;
    let live = true;
    let opened: Task | null = null;
    void openDocument(bytes.bytes)
      .then(async (task) => {
        opened = task;
        const d = await task.promise;
        // Geometry for every page up front: it is metadata, not pixels, and it is what
        // lets the placeholders below be the right size.
        const read: Page[] = [];
        for (let i = 1; i <= d.numPages; i += 1) {
          const p = await d.getPage(i);
          const v = p.getViewport({ scale: 1 });
          read.push({ index: i, width: v.width, height: v.height });
        }
        if (!live) return;
        setDoc(d);
        setPages(read);
      })
      .catch((err: unknown) => {
        // What a reader says about a malformed document names parts of a file format,
        // which is not what belongs on screen. The pane says the one actionable thing.
        console.warn(`${path} could not be read`, err);
        if (live) setFailed(true);
      });
    return () => {
      live = false;
      void opened?.destroy();
    };
  }, [bytes, path]);

  if (bytes.state === "failed" || failed)
    return <p className="p-4 text-xs text-destructive">{S.viewerFailed}</p>;

  return (
    <div ref={column} className="h-full overflow-auto bg-background px-6 py-4">
      {doc === null ? (
        <p className="text-xs text-muted-foreground">{S.loading}</p>
      ) : (
        <div className="mx-auto flex max-w-4xl flex-col gap-4">
          {pages.map((page) => (
            <PageView key={page.index} doc={doc} page={page} width={Math.min(width - 48, 896)} />
          ))}
        </div>
      )}
    </div>
  );
}

// app/src/lib/viewers/PdfViewer.svelte
<script lang="ts">
  import type { PDFDocumentLoadingTask, PDFDocumentProxy } from 'pdfjs-dist/legacy/build/pdf.mjs';
  import { tick } from 'svelte';
  import './pdf-text-layer.css';
  import type { BytesProps } from './registry';

  let { entry, bytes }: BytesProps = $props();

  // Rendered by pdf.js into canvases, not handed to the browser's own viewer in an
  // iframe: WKWebView draws nothing for a PDF in a subframe served over a custom scheme,
  // which is where a context's files come from. The legacy build, so an older macOS's
  // WebKit can run it.

  /// What pdf.js asks for by URL while it works (see `pdfjsAssets` in `vite.config.ts`).
  /// Absolute, because the worker resolves them and it has no page to be relative to.
  const assets = (dir: string) => new URL(`/pdfjs/${dir}/`, location.href).href;

  type Pdfjs = typeof import('pdfjs-dist/legacy/build/pdf.mjs');

  let host: HTMLDivElement;
  /// Each page's box in CSS pixels, and the scale from the PDF's own units to it.
  let pages = $state<{ width: number; height: number; scale: number }[]>([]);
  let failed = $state<string | null>(null);

  $effect(() => {
    let task: PDFDocumentLoadingTask | null = null;
    let doc: PDFDocumentProxy | null = null;
    let observer: IntersectionObserver | null = null;
    let cancelled = false;

    (async () => {
      try {
        const pdfjs = await import('pdfjs-dist/legacy/build/pdf.mjs');
        const worker = await import('pdfjs-dist/legacy/build/pdf.worker.min.mjs?url');
        pdfjs.GlobalWorkerOptions.workerSrc = worker.default;
        // A copy: pdf.js hands the buffer to its worker, which detaches it here.
        task = pdfjs.getDocument({
          data: new Uint8Array(bytes.slice(0)),
          cMapUrl: assets('cmaps'),
          standardFontDataUrl: assets('standard_fonts'),
          iccUrl: assets('iccs'),
          wasmUrl: assets('wasm'),
        });
        doc = await task.promise;
        if (cancelled) return;

        // Every page's box first, at the width the panel has, so the scrollbar is the
        // document's length before a single page is drawn.
        const fit = Math.max(200, host.clientWidth - 48);
        const sizes = [];
        for (let n = 1; n <= doc.numPages; n++) {
          const page = await doc.getPage(n);
          const base = page.getViewport({ scale: 1 });
          const scale = fit / base.width;
          sizes.push({ width: base.width * scale, height: base.height * scale, scale });
        }
        if (cancelled) return;
        pages = sizes;

        // Then each page as it comes near the viewport, once.
        const drawn = new Set<number>();
        observer = new IntersectionObserver(
          (seen) => {
            for (const item of seen) {
              const n = Number((item.target as HTMLElement).dataset.page);
              if (!item.isIntersecting || drawn.has(n) || !doc) continue;
              drawn.add(n);
              void draw(pdfjs, doc, n, item.target as HTMLElement);
            }
          },
          { root: host, rootMargin: '600px 0px' },
        );
        // The page boxes exist once the DOM has caught up with `pages`.
        await tick();
        for (const el of host.querySelectorAll('[data-page]')) observer.observe(el);
      } catch (e) {
        if (!cancelled) failed = e instanceof Error ? e.message : String(e);
      }
    })();

    return () => {
      cancelled = true;
      observer?.disconnect();
      // The task, not the document: it takes the document and its worker down with it.
      void task?.destroy();
    };
  });

  /// Page `n` into its box: the picture on the canvas, and the text laid over it where
  /// each glyph sits, transparent, so it can be selected and copied.
  async function draw(pdfjs: Pdfjs, doc: PDFDocumentProxy, n: number, box: HTMLElement) {
    const page = await doc.getPage(n);
    const { scale } = pages[n - 1];
    const viewport = page.getViewport({ scale });

    // Sharp on a Retina screen: the backing store is the device's pixels, the box is CSS's.
    const ratio = window.devicePixelRatio || 1;
    const canvas = box.querySelector('canvas')!;
    canvas.width = Math.floor(viewport.width * ratio);
    canvas.height = Math.floor(viewport.height * ratio);
    await page.render({ canvas, viewport: page.getViewport({ scale: scale * ratio }) }).promise;

    const text = box.querySelector<HTMLElement>('.textLayer')!;
    await new pdfjs.TextLayer({
      textContentSource: page.streamTextContent(),
      container: text,
      viewport,
    }).render();
  }
</script>

<div class="pdf" bind:this={host} aria-label={entry.name}>
  {#if failed}
    <p class="note">That PDF could not be opened: {failed}</p>
  {:else if pages.length === 0}
    <p class="note">Loading…</p>
  {/if}
  {#each pages as size, i (i)}
    <div
      class="page"
      data-page={i + 1}
      style:width="{size.width}px"
      style:height="{size.height}px"
      style:--total-scale-factor={size.scale}
    >
      <canvas></canvas>
      <div class="textLayer"></div>
    </div>
  {/each}
</div>

<style>
  .pdf {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 16px;
    height: 100%;
    padding: 24px;
    overflow: auto;
    /* The letterboxing around a page, rather than the panel's own background. */
    background: var(--bg-sunken);
    box-sizing: border-box;
  }
  .page {
    position: relative;
    flex: none;
    background: white;
    box-shadow: var(--shadow-md);
  }
  canvas { display: block; width: 100%; height: 100%; }
  .note { margin: 40px 0; font-size: var(--fs-md); color: var(--text-faint); }
</style>
